# Generated by Django 4.1.7 on 2023-08-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poductdb',
            name='product_price',
            field=models.IntegerField(null=True),
        ),
    ]
