# Generated by Django 4.1.7 on 2023-08-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_alter_poductdb_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poductdb',
            name='product_price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
