# Generated by Django 4.1.7 on 2023-08-13 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0003_alter_poductdb_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poductdb',
            name='product_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
