# Generated by Django 4.1.7 on 2023-08-08 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontendapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupdb',
            name='Confrim_pswd',
        ),
        migrations.RemoveField(
            model_name='signupdb',
            name='Phone',
        ),
    ]
