# Generated by Django 4.1.7 on 2023-08-10 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontendapp', '0003_cartdb_signupdb_quantity_signupdb_tprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupdb',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='signupdb',
            name='tprice',
        ),
        migrations.AddField(
            model_name='cartdb',
            name='quantity',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='cartdb',
            name='tprice',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
