# Generated by Django 4.1.7 on 2023-08-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontendapp', '0005_remove_cartdb_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdb',
            name='tprice',
            field=models.IntegerField(null=True),
        ),
    ]
