# Generated by Django 4.1.7 on 2023-08-12 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontendapp', '0006_alter_cartdb_tprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdb',
            name='username',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
