# Generated by Django 4.1.7 on 2023-08-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontendapp', '0007_cartdb_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdb',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
