# Generated by Django 4.1.7 on 2023-08-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontendapp', '0009_checkoutdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutdb',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='checkoutdb',
            name='postoffice',
            field=models.IntegerField(null=True),
        ),
    ]
